image: ghcr.io/notional-labs/cosmos

tasks:
  - name: install tools
    command: |
      go install mvdan.cc/gofumpt@latest
      go install golang.org/x/tools/cmd/goimports@latest
      sudo pacman -Syyu clang --noconfirm
      sudo bash scripts/protoc/install-tools.sh
