version: 1
genesis:
  chain-id: ollo-testnet-2
  bank:
    send_enabled: true

accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
  vue:
    path: "vue"
  dart:
    path: "flutter"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
