version: '3.8'
services:
  ollod:
    restart: always
    hostname: ollo
    volumes:
    - ./data/ollolocal-1:/ollo/.ollo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 26657:26657
    - 26656:26656
    - 1317:1317
    - 9090:9090
