version: '3.8'
networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16

services:

  node0:
    container_name: node0
    restart: always
    hostname: ollo
    volumes:
    - ./data/ollolocal-1:/ollo/.ollo
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      local:
        ipv4_address: 192.167.10.4
    command:
      - /ollod start --home /ollo
    ports:
    - 26657:26657
    - 26656:26656
    - 1317:1317
    - 9090:9090
