// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ollo/grants/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the grants module's genesis state.
type GenesisState struct {
	// params defines all the parameters for the module
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// auctions define the auction interface for genesis state; the module
	// supports FixedPriceAuction or BatchAuction
	Auctions []*types.Any `protobuf:"bytes,2,rep,name=auctions,proto3" json:"auctions,omitempty"`
	// allowed_bidder_records define the allowed bidder records for the auction
	AllowedBidderRecords []AllowedBidderRecord `protobuf:"bytes,3,rep,name=allowed_bidder_records,json=allowedBidderRecords,proto3" json:"allowed_bidder_records"`
	// bids define the bid records used for genesis state
	Bids []Bid `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids"`
	// vesting_queues define the vesting queue records used for genesis
	// state
	VestingQueues []VestingQueue `protobuf:"bytes,5,rep,name=vesting_queues,json=vestingQueues,proto3" json:"vesting_queues"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0514526f77312ab0, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenesisState)(nil), "ollo.grants.v1.GenesisState")
}

func init() { proto.RegisterFile("ollo/grants/v1/genesis.proto", fileDescriptor_0514526f77312ab0) }

var fileDescriptor_0514526f77312ab0 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0xe2, 0x40,
	0x18, 0xc7, 0x5b, 0x60, 0x09, 0x29, 0x2c, 0x87, 0x2e, 0x21, 0x85, 0x25, 0x85, 0xec, 0x5e, 0x48,
	0x36, 0xcc, 0x04, 0xd6, 0x93, 0x07, 0x13, 0x9a, 0x18, 0xc3, 0x4d, 0x31, 0xf1, 0xe0, 0xa5, 0x99,
	0xb6, 0xe3, 0xd8, 0xa4, 0x74, 0xb0, 0x33, 0xad, 0xf2, 0x06, 0x1e, 0x7d, 0x04, 0x1e, 0xc2, 0x87,
	0x20, 0x9e, 0x38, 0x7a, 0x32, 0x06, 0x2e, 0xfa, 0x16, 0xa6, 0x33, 0xc5, 0x68, 0xf5, 0xd6, 0xef,
	0xfb, 0xfd, 0xbe, 0xef, 0xfb, 0x67, 0xaa, 0x75, 0x68, 0x10, 0x50, 0x48, 0x22, 0x14, 0x72, 0x06,
	0x93, 0x21, 0x24, 0x38, 0xc4, 0xcc, 0x67, 0x60, 0x1e, 0x51, 0x4e, 0xf5, 0x7a, 0x4a, 0x81, 0xa4,
	0x20, 0x19, 0xb6, 0x5b, 0x2e, 0x65, 0x33, 0xca, 0x6c, 0x41, 0xa1, 0x2c, 0xa4, 0xda, 0x6e, 0x10,
	0x4a, 0xa8, 0xec, 0xa7, 0x5f, 0x59, 0xb7, 0x45, 0x28, 0x25, 0x01, 0x86, 0xa2, 0x72, 0xe2, 0x0b,
	0x88, 0xc2, 0x45, 0x86, 0x7e, 0xe7, 0x2f, 0xcb, 0x2b, 0xdf, 0xc3, 0x39, 0x8a, 0xd0, 0x2c, 0x83,
	0x7f, 0x5e, 0x0b, 0x5a, 0xed, 0x48, 0xe6, 0x3c, 0xe5, 0x88, 0x63, 0x7d, 0x4f, 0x2b, 0x4b, 0xc1,
	0x50, 0x7b, 0x6a, 0xbf, 0x3a, 0x6a, 0x82, 0xcf, 0xb9, 0xc1, 0xb1, 0xa0, 0x56, 0x69, 0xf5, 0xd4,
	0x55, 0xa6, 0x99, 0xab, 0x1f, 0x68, 0x15, 0x14, 0xbb, 0xdc, 0xa7, 0x21, 0x33, 0x0a, 0xbd, 0x62,
	0xbf, 0x3a, 0x6a, 0x00, 0x19, 0x17, 0xec, 0xe2, 0x82, 0x71, 0xb8, 0xb0, 0x6a, 0x0f, 0xf7, 0x83,
	0xca, 0x58, 0x9a, 0x93, 0xe9, 0xfb, 0x8c, 0x6e, 0x6b, 0x4d, 0x14, 0x04, 0xf4, 0x1a, 0x7b, 0xb6,
	0xe3, 0x7b, 0x1e, 0x8e, 0xec, 0x08, 0xbb, 0x34, 0xf2, 0x98, 0x51, 0x14, 0xdb, 0xfe, 0xe6, 0x53,
	0x8c, 0xa5, 0x6d, 0x09, 0x79, 0x2a, 0xdc, 0x2c, 0x52, 0x03, 0x7d, 0x45, 0x4c, 0x1f, 0x68, 0x25,
	0xc7, 0xf7, 0x98, 0x51, 0x12, 0xeb, 0x7e, 0xe5, 0xd7, 0x59, 0xfe, 0x6e, 0x5c, 0x68, 0xfa, 0x44,
	0xab, 0x27, 0x98, 0x71, 0x3f, 0x24, 0xf6, 0x55, 0x8c, 0x63, 0xcc, 0x8c, 0x1f, 0x62, 0xb0, 0x93,
	0x1f, 0x3c, 0x93, 0xd6, 0x49, 0x2a, 0x65, 0x1b, 0x7e, 0x26, 0x1f, 0x7a, 0x6c, 0xbf, 0x72, 0xbb,
	0xec, 0x2a, 0x2f, 0xcb, 0xae, 0x62, 0x1d, 0xae, 0x36, 0xa6, 0xba, 0xde, 0x98, 0xea, 0xf3, 0xc6,
	0x54, 0xef, 0xb6, 0xa6, 0xb2, 0xde, 0x9a, 0xca, 0xe3, 0xd6, 0x54, 0xce, 0xff, 0x11, 0x9f, 0x5f,
	0xc6, 0x0e, 0x70, 0xe9, 0x0c, 0xa6, 0x07, 0x06, 0x8c, 0xa3, 0xf4, 0x61, 0x44, 0x01, 0x6f, 0x76,
	0x3f, 0x8f, 0x2f, 0xe6, 0x98, 0x39, 0x65, 0xf1, 0xa2, 0xff, 0xdf, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x1f, 0x36, 0xf9, 0x61, 0x6f, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VestingQueues) > 0 {
		for iNdEx := len(m.VestingQueues) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VestingQueues[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Bids) > 0 {
		for iNdEx := len(m.Bids) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Bids[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.AllowedBidderRecords) > 0 {
		for iNdEx := len(m.AllowedBidderRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AllowedBidderRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Auctions) > 0 {
		for iNdEx := len(m.Auctions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Auctions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Auctions) > 0 {
		for _, e := range m.Auctions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AllowedBidderRecords) > 0 {
		for _, e := range m.AllowedBidderRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Bids) > 0 {
		for _, e := range m.Bids {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.VestingQueues) > 0 {
		for _, e := range m.VestingQueues {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auctions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Auctions = append(m.Auctions, &types.Any{})
			if err := m.Auctions[len(m.Auctions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedBidderRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedBidderRecords = append(m.AllowedBidderRecords, AllowedBidderRecord{})
			if err := m.AllowedBidderRecords[len(m.AllowedBidderRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bids", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bids = append(m.Bids, Bid{})
			if err := m.Bids[len(m.Bids)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingQueues", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VestingQueues = append(m.VestingQueues, VestingQueue{})
			if err := m.VestingQueues[len(m.VestingQueues)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
