name: Compile OLLO

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [darwin, linux, windows]
        include:
          - targetos: darwin
            arch: arm64
          - targetos: windows
            arch: arm64
    name: ollo ${{ matrix.arch }} ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.18'
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile OLLO
        run: |
          go mod download
          cd cmd/ollod
          go build .
      - uses: actions/upload-artifact@v2
        with:
          name: ollod ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/ollod/ollod
